name: Deploy 
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Scripts
      shell: bash
      run: |
        python3 --version
        pip3 --version
        # virtualenv --version # doesn't work here
                
        mkdir -p awscli-lambda awscli-lambda/layer
        cd awscli-lambda && python3.8 -m venv env
        cd env && source bin/activate
        pip install awscli
        cd ../layer/
        cp -r ../env/lib/python3.8/site-packages/ .
        cp ../env/bin/aws .

        head -1 aws
        sed -i '1s|.*|#!/var/lang/bin/python|' aws
        head -1 aws
        zip -r ../lambda-awscli.zip * > /dev/null
        cd ..
        ls lambda-awscli.zip
        
        
