name: Deploy 
on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1

  
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Scripts
      shell: bash
      run: |
        python3 --version
        pip3 --version
        # virtualenv --version # doesn't work here
                
        mkdir -p awscli-lambda awscli-lambda/layer
        cd awscli-lambda && python3.8 -m venv env
        cd env && source bin/activate
        pip install awscli
        cd ../layer/
        cp -r ../env/lib/python3.8/site-packages/ .
        cp ../env/bin/aws .

        head -1 aws
        sed -i '1s|.*|#!/var/lang/bin/python|' aws
        head -1 aws
        zip -r ../lambda-awscli.zip * > /dev/null
        cd ..
        
        touch lambda_function.py
        zip lambda-awscli.zip lambda_function.py
        ls lambda-awscli.zip
        aws lambda update-function-code --function-name rds-migrate --zip-file fileb://lambda-awscli.zip
        
