name: Deploy 
on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1

  
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Scripts
      shell: bash
      run: |
        set -e
        aws sts get-caller-identity | grep Account
        zip lambda-awscli.zip lambda_function.py
        ls lambda-awscli.zip
        aws lambda update-function-code --function-name pythondemo --zip-file fileb://lambda-awscli.zip
        
